import './global.css'
import NavBar from "@/component/NavBar"

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<NavBar />
				{children}</body>
		</html>
	)
}
